#!/bin/bash

echo "🚀 Setting up iOS development environment..."
echo ""

# Get local IP address
IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)

if [ -z "$IP" ]; then
    echo "❌ Could not auto-detect IP address"
    echo ""
    echo "Please find your IP address manually:"
    echo "  macOS: System Preferences > Network"
    echo "  Or run: ifconfig | grep 'inet '"
    echo ""
    echo "Then create .env.ios with:"
    echo "  VITE_API_URL=http://YOUR_IP:5000/api"
    echo "  VITE_SOCKET_URL=http://YOUR_IP:5000"
    exit 1
fi

echo "✅ Detected IP address: $IP"
echo ""

# Create .env.ios file
cat > .env.ios << EOF
# iOS Development Environment
# Auto-generated by setup-ios-dev.sh
# Your computer's IP: $IP

VITE_API_URL=http://$IP:5000/api
VITE_SOCKET_URL=http://$IP:5000
VITE_GOOGLE_MAPS_API_KEY=AIzaSyBmFCy71VLlgNcbvEQNu2azuSM5flgArE4

# Analytics Configuration (PostHog) - Disabled for development
# VITE_POSTHOG_KEY=your_posthog_project_key_here
# VITE_POSTHOG_HOST=https://app.posthog.com
EOF

echo "✅ Created .env.ios"

# Backup current .env if it exists
if [ -f .env ]; then
    cp .env .env.backup
    echo "✅ Backed up existing .env to .env.backup"
fi

# Copy to .env
cp .env.ios .env
echo "✅ Activated iOS environment (.env.ios → .env)"
echo ""

# Build and sync
echo "🔨 Building web app..."
npm run build

if [ $? -ne 0 ]; then
    echo "❌ Build failed"
    exit 1
fi

echo ""
echo "📱 Syncing to iOS..."
npx cap sync ios

if [ $? -ne 0 ]; then
    echo "❌ Sync failed"
    exit 1
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start your backend server:"
echo "   cd ../backend"
echo "   npm start"
echo ""
echo "2. Make sure backend listens on 0.0.0.0:5000"
echo "   (not just localhost)"
echo ""
echo "3. Open Xcode:"
echo "   npm run cap:open:ios"
echo ""
echo "4. Run the app from Xcode (Cmd + R)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 Your API Configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  API URL: http://$IP:5000/api"
echo "  Socket URL: http://$IP:5000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  Important Notes:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • iOS device must be on same WiFi as your computer"
echo "  • If IP changes, re-run this script"
echo "  • For web development, restore .env.backup"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
