import { PackingItem, PackingCategory } from '../types/packing';
import { CATEGORY_LABELS } from './defaultPackingTemplate';

const categoryLabels: Record<PackingCategory, string> = CATEGORY_LABELS;

export const packingExportService = {
  /**
   * Export packing list as PDF
   */
  async exportAsPDF(tripTitle: string, items: PackingItem[]): Promise<void> {
    // Group items by category
    const itemsByCategory = this.groupByCategory(items);

    // Create print-friendly HTML
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to export PDF');
      return;
    }

    const html = this.generatePrintHTML(tripTitle, itemsByCategory);
    printWindow.document.write(html);
    printWindow.document.close();

    // Wait for content to load, then print
    printWindow.onload = () => {
      printWindow.print();
    };
  },

  /**
   * Generate print-friendly HTML
   */
  generatePrintHTML(tripTitle: string, itemsByCategory: Map<PackingCategory, PackingItem[]>): string {
    const categories = Array.from(itemsByCategory.keys());
    
    let itemsHTML = '';
    categories.forEach((category) => {
      const items = itemsByCategory.get(category) || [];
      if (items.length === 0) return;

      itemsHTML += `
        <div class="category">
          <h2>${categoryLabels[category]}</h2>
          <ul class="items">
            ${items.map(item => `
              <li>
                <input type="checkbox" ${item.is_checked ? 'checked' : ''} />
                <span class="${item.is_checked ? 'checked' : ''}">${item.item}</span>
                ${!item.is_custom ? '<span class="badge">Suggested</span>' : ''}
              </li>
            `).join('')}
          </ul>
        </div>
      `;
    });

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>${tripTitle} - Packing List</title>
          <style>
            @media print {
              @page {
                margin: 1cm;
              }
            }
            
            body {
              font-family: Arial, sans-serif;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            
            h1 {
              color: #1f2937;
              border-bottom: 3px solid #3b82f6;
              padding-bottom: 10px;
              margin-bottom: 30px;
            }
            
            .category {
              margin-bottom: 30px;
              page-break-inside: avoid;
            }
            
            .category h2 {
              color: #374151;
              font-size: 18px;
              margin-bottom: 15px;
              background-color: #f3f4f6;
              padding: 10px;
              border-radius: 5px;
            }
            
            .items {
              list-style: none;
              padding: 0;
            }
            
            .items li {
              padding: 8px 0;
              border-bottom: 1px solid #e5e7eb;
              display: flex;
              align-items: center;
              gap: 10px;
            }
            
            .items li:last-child {
              border-bottom: none;
            }
            
            .items input[type="checkbox"] {
              width: 18px;
              height: 18px;
              cursor: pointer;
            }
            
            .items span.checked {
              text-decoration: line-through;
              color: #9ca3af;
            }
            
            .badge {
              background-color: #dbeafe;
              color: #1e40af;
              padding: 2px 8px;
              border-radius: 4px;
              font-size: 12px;
              margin-left: auto;
            }
            
            .footer {
              margin-top: 40px;
              text-align: center;
              color: #6b7280;
              font-size: 12px;
              border-top: 1px solid #e5e7eb;
              padding-top: 20px;
            }
            
            @media print {
              .no-print {
                display: none;
              }
            }
          </style>
        </head>
        <body>
          <h1>${tripTitle} - Packing List</h1>
          ${itemsHTML}
          <div class="footer">
            <p>Generated by Journo • ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `;
  },

  /**
   * Group items by category
   */
  groupByCategory(items: PackingItem[]): Map<PackingCategory, PackingItem[]> {
    const grouped = new Map<PackingCategory, PackingItem[]>();
    
    items.forEach((item) => {
      if (!item.category) return;
      
      if (!grouped.has(item.category)) {
        grouped.set(item.category, []);
      }
      grouped.get(item.category)!.push(item);
    });

    return grouped;
  },

  /**
   * Detect duplicate items
   */
  detectDuplicates(items: PackingItem[]): { item1: PackingItem; item2: PackingItem }[] {
    const duplicates: { item1: PackingItem; item2: PackingItem }[] = [];
    
    for (let i = 0; i < items.length; i++) {
      for (let j = i + 1; j < items.length; j++) {
        if (this.areSimilar(items[i].item, items[j].item)) {
          duplicates.push({ item1: items[i], item2: items[j] });
        }
      }
    }

    return duplicates;
  },

  /**
   * Check if two item names are similar
   */
  areSimilar(name1: string, name2: string): boolean {
    const normalize = (str: string) => 
      str.toLowerCase()
        .replace(/[^a-z0-9]/g, '')
        .trim();

    const n1 = normalize(name1);
    const n2 = normalize(name2);

    // Exact match after normalization
    if (n1 === n2) return true;

    // Check if one contains the other
    if (n1.includes(n2) || n2.includes(n1)) {
      // Only consider similar if length difference is small
      const lengthDiff = Math.abs(n1.length - n2.length);
      return lengthDiff <= 3;
    }

    return false;
  },

  /**
   * Open print-friendly view
   */
  openPrintView(tripTitle: string, items: PackingItem[]): void {
    const itemsByCategory = this.groupByCategory(items);
    const html = this.generatePrintHTML(tripTitle, itemsByCategory);
    
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to open print view');
      return;
    }

    printWindow.document.write(html);
    printWindow.document.close();
  },
};
